/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import flow3.Controller;
import flow3.PersonalInterface;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.JOptionPane;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author Valentina
 */
public class AddToFile extends javax.swing.JFrame {

    /**
     * Creates new form AddToFile
     */
    PersonalInterface control;
    private String fileName;
    private String line;
    private String gameName;
    private String pName1;
    private String pName2;
    private String text1;
    private String text2;

    public AddToFile() {
        initComponents();
        
    }

    AddToFile(String line, String pName1, String pName2) {
        this();
        this.pName1=pName1;
        this.pName2=pName2;
        text1 = this.pName1;
        text2 = this.pName2;
        control = new Controller();
        this.line=line;
        control.load(this.line+".txt");
        fileName=this.line+".txt";
        gameName=this.line;
        System.out.println(line);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
     
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SlovAdd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        EngAdd = new javax.swing.JTextField();
        AddWord = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Question");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 110, 70, 17);

        SlovAdd.setBackground(new java.awt.Color(23, 24, 67));
        SlovAdd.setForeground(new java.awt.Color(255, 255, 255));
        SlovAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SlovAddActionPerformed(evt);
            }
        });
        jPanel1.add(SlovAdd);
        SlovAdd.setBounds(10, 130, 138, 28);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Answer");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 240, 60, 17);

        EngAdd.setBackground(new java.awt.Color(89, 95, 143));
        EngAdd.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(EngAdd);
        EngAdd.setBounds(10, 260, 138, 28);

        AddWord.setBackground(new java.awt.Color(0, 0, 102));
        AddWord.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AddWord.setForeground(new java.awt.Color(255, 255, 255));
        AddWord.setText("Add Question");
        AddWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddWordActionPerformed(evt);
            }
        });
        jPanel1.add(AddWord);
        AddWord.setBounds(100, 190, 120, 30);

        Back.setBackground(new java.awt.Color(78, 78, 149));
        Back.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back);
        Back.setBounds(620, 230, 61, 25);

        Exit.setBackground(new java.awt.Color(68, 72, 123));
        Exit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setText("EXIT");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit);
        Exit.setBounds(620, 270, 61, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("What question yould you like to add?");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(180, 0, 410, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Valentina\\Documents\\NetBeansProjects\\Flow3big\\src\\adding.jpg")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 728, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    

    
    private void SlovAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SlovAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SlovAddActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizzGame(gameName, text1, text2).setVisible(true);
            }
        });
        this.setVisible(false);
    }//GEN-LAST:event_BackActionPerformed

    private void AddWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddWordActionPerformed
        // TODO add your handling code here:
        

        //method that adds words to the quizz file and checks if they are there or not, or if you wrote both words
        if (control.checkGuess(SlovAdd.getText(), EngAdd.getText())) {
            InputStream in;
        try{
        in = new FileInputStream(new File ("C:\\Users\\Valentina\\Documents\\NetBeansProjects\\Flow3big\\src\\button-12.wav"));
            AudioStream audioS= new AudioStream(in);
            AudioPlayer.player.start(audioS);
           
             JOptionPane.showMessageDialog(this, "The words already exist!",
                    "isThere!", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);}
            
            
           
            
        } else if (SlovAdd.getText().equals("") || EngAdd.getText().equals("")) {
            
            InputStream in;
        try{
        in = new FileInputStream(new File ("C:\\Users\\Valentina\\Documents\\NetBeansProjects\\Flow3big\\src\\button-12.wav"));
            AudioStream audioS= new AudioStream(in);
            AudioPlayer.player.start(audioS);
           
            JOptionPane.showMessageDialog(this, "Both words should be added!",
                    "both", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);}
            
        } else if (control.lookup(SlovAdd.getText()) != null) //|| !control.lookup(EngAdd.getText()).equals(EngAdd.getText()) )
        {
            
              InputStream in;
        try{
        in = new FileInputStream(new File ("C:\\Users\\Valentina\\Documents\\NetBeansProjects\\Flow3big\\src\\button-12.wav"));
            AudioStream audioS= new AudioStream(in);
            AudioPlayer.player.start(audioS);
           
           JOptionPane.showMessageDialog(this, "The question exists!",
                    "oneOfThem1", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);}
            
        } else if (control.lookup(EngAdd.getText()) != null) {
            
             InputStream in;
        try{
        in = new FileInputStream(new File ("C:\\Users\\Valentina\\Documents\\NetBeansProjects\\Flow3big\\src\\button-12.wav"));
            AudioStream audioS= new AudioStream(in);
            AudioPlayer.player.start(audioS);
           
           JOptionPane.showMessageDialog(this, "The answer exists!",
                    "oneOfThem1", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);}
            

        } else {
            control.add(SlovAdd.getText()+","+ EngAdd.getText());
            control.save(fileName);
            SlovAdd.setText("");
            EngAdd.setText("");
        }
    }//GEN-LAST:event_AddWordActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddWord;
    private javax.swing.JButton Back;
    private javax.swing.JTextField EngAdd;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField SlovAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
