/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import flow3.Controller;
import flow3.PersonalInterface;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.JOptionPane;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author Valentina
 */
public class QuizzGame extends javax.swing.JFrame {

    /**
     * Creates new form QuizzGame
     */
    PersonalInterface quizz;
   
    
    private String gameName;
    private String scoreFile;
    private String line;
    private String name1;
    private String name2;
    private String score1;
    private String tami1;
    private String tami2;
    private int prevScore1;
    private int prevScore2;
    private int guessB;
    private String oldScore;
   
  
    
    public QuizzGame() {
        
        initComponents();
        
        
    }

   
    QuizzGame(String gameName, String name1, String name2) {
        
        this();
        this.name1= name1;
        this.name2=name2;
        quizz= new Controller();
        scoreFile="Score.txt";
        oldScore=null;
        
        quizz.load(scoreFile);
        this.gameName=gameName;
        if(name2.equals("computer")){
            Player2.setText("computer");
            Player1.setText(name1);
            score1= quizz.lookup(name1);
            System.out.println(name1);
            System.out.println(score1);
            prevScore1=10;
            ScoreField2.setText("Good Luck!");
            
        }
        else if(name2.equals("inFolder"))
        {
            Player2.setText("computer");
            Player1.setText(name1);
            score1=quizz.lookup(name1);
            prevScore1=Integer.parseInt(score1);
            ScoreField2.setText("Good Luck!");
            oldScore = name1+","+score1;
        }
        else{
            Player1.setText(name1);
            Player2.setText(name2);
            scoreFile="friends.txt";
            
            prevScore1=0;
            prevScore2=0;
        }
            tami1=null;
            tami2=null;
        guessB=0;
        
        
        quizz.load(this.gameName+".txt");
        jGameName.setText(this.gameName);
        line=this.gameName;
        //changes image according to the quizz you choose to play
        Image.setIcon(new javax.swing.ImageIcon("C:\\Users\\Valentina\\Documents\\NetBeansProjects\\Flow3big\\src\\"+this.gameName+".jpg"));
       
        System.out.println(this.gameName);
    }

     
     

        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jQuestion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jAnswer = new javax.swing.JTextField();
        GuessButton = new javax.swing.JButton();
        lookUpButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ScoreField1 = new javax.swing.JTextField();
        jGameName = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Player2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Player1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ScoreField2 = new javax.swing.JTextField();
        Image = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Question:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 270, 80, 30);

        jQuestion.setBackground(new java.awt.Color(0, 0, 0));
        jQuestion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jQuestion.setForeground(new java.awt.Color(255, 255, 255));
        jQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQuestionActionPerformed(evt);
            }
        });
        jPanel1.add(jQuestion);
        jQuestion.setBounds(110, 270, 201, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Answer:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 320, 70, 20);

        jAnswer.setBackground(new java.awt.Color(0, 0, 0));
        jAnswer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jAnswer.setForeground(new java.awt.Color(255, 255, 255));
        jAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnswerActionPerformed(evt);
            }
        });
        jPanel1.add(jAnswer);
        jAnswer.setBounds(110, 320, 201, 29);

        GuessButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GuessButton.setText("Guess");
        GuessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuessButtonActionPerformed(evt);
            }
        });
        jPanel1.add(GuessButton);
        GuessButton.setBounds(350, 310, 90, 25);

        lookUpButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lookUpButton.setText("Look up");
        lookUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookUpButtonActionPerformed(evt);
            }
        });
        jPanel1.add(lookUpButton);
        lookUpButton.setBounds(140, 500, 83, 25);

        newButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        newButton.setText("New");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });
        jPanel1.add(newButton);
        newButton.setBounds(260, 500, 59, 25);

        nextButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nextButton.setText("Add Words");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        jPanel1.add(nextButton);
        nextButton.setBounds(180, 560, 101, 25);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(830, 10, 110, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Score 1: ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 370, 80, 30);

        ScoreField1.setBackground(new java.awt.Color(0, 0, 0));
        ScoreField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ScoreField1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(ScoreField1);
        ScoreField1.setBounds(110, 370, 201, 29);

        jGameName.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jGameName.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(jGameName);
        jGameName.setBounds(20, 10, 258, 59);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(350, 370, 75, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Player 2:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 220, 80, 30);

        Player2.setBackground(new java.awt.Color(0, 0, 0));
        Player2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Player2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Player2);
        Player2.setBounds(110, 220, 200, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Player 1:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 170, 80, 22);

        Player1.setBackground(new java.awt.Color(0, 0, 0));
        Player1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Player1);
        Player1.setBounds(110, 170, 200, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 51));
        jLabel7.setText("Score 2:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 420, 80, 30);

        ScoreField2.setBackground(new java.awt.Color(0, 0, 0));
        ScoreField2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(ScoreField2);
        ScoreField2.setBounds(110, 420, 200, 30);

        Image.setIcon(new javax.swing.ImageIcon("C:\\Users\\Valentina\\Documents\\NetBeansProjects\\Flow3big\\src\\Music.jpg")); // NOI18N
        jPanel1.add(Image);
        Image.setBounds(0, 0, 950, 650);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("If you want to have an image, you have to import one with the same name as the game you just added, and the dimensions 960X657. Have hun!");
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 560, 800, 60);

        jMenu1.setText("Add Games");

        jMenuItem3.setText("Add Game");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Scores");

        jMenuItem1.setText("Player&Score");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Player");

        jMenuItem4.setText("Choose how to Play");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 947, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQuestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jQuestionActionPerformed

    private void jAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAnswerActionPerformed

    private void GuessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuessButtonActionPerformed
        // TODO add your handling code here:
        //when this button is clicked you get to add score to your previous score
        guessB++;
        if(jQuestion.getText().equals("") || jAnswer.getText().equals(""))
        {
            
             InputStream in;
        try{
        in = new FileInputStream(new File ("C:\\Users\\Valentina\\Documents\\NetBeansProjects\\Flow3big\\src\\button-12.wav"));
            AudioStream audioS= new AudioStream(in);
            AudioPlayer.player.start(audioS);
           
            JOptionPane.showMessageDialog(this, "Both words must be completed.",
            "bothWord", JOptionPane.INFORMATION_MESSAGE);
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);}
           
        }
        else if(quizz.checkGuess(jQuestion.getText(), jAnswer.getText()))
        { if(name2.equals("computer") || name2.equals("inFolder")){
            
            
            prevScore1 += quizz.scores();
            
            tami1 = Integer.toString(prevScore1);
            
            ScoreField1.setText(tami1);
            
            jQuestion.setText("");
            jAnswer.setText("");
            }
        else{
           if(guessB%2 != 0){
            
            prevScore1 += 5;
            
            tami1 = Integer.toString(prevScore1);
            
            ScoreField1.setText(tami1);
            jQuestion.setText("");
            jAnswer.setText("");
}
        
        else {
           prevScore2 += 5;
            
            tami2 = Integer.toString(prevScore2);
            
            ScoreField2.setText(tami2);
            jQuestion.setText("");
            jAnswer.setText("");
        }
        }
        }
        else {
            jQuestion.setText("");
            jAnswer.setText("");
        }
        
    }//GEN-LAST:event_GuessButtonActionPerformed

    private void lookUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookUpButtonActionPerformed
       
        //shows you the answer to the given question
        if(jQuestion.getText().equals("")){
            
             InputStream in;
        try{
        in = new FileInputStream(new File ("C:\\Users\\Valentina\\Documents\\NetBeansProjects\\Flow3big\\src\\button-12.wav"));
            AudioStream audioS= new AudioStream(in);
            AudioPlayer.player.start(audioS);
           
            JOptionPane.showMessageDialog(this, "There is no word to be translated.",
            "noWord", JOptionPane.INFORMATION_MESSAGE);
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);}
        
        }
        else {
        jAnswer.setText(quizz.lookup(jQuestion.getText()));
        jQuestion.setText("");
        }
    }//GEN-LAST:event_lookUpButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddToFile(line,name1, name2).setVisible(true);
            }
        });
        this.setVisible(false);
    }//GEN-LAST:event_nextButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        // TODO add your handling code here:
        jAnswer.setText("");
        jQuestion.setText(quizz.getRandomQuestion());
    }//GEN-LAST:event_newButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        //method used in the submit button which will save to the file and delete the previous entry the person had, while adding the new score
        if(name2.equals("computer")){
             quizz.loadQuizz(scoreFile);
           quizz.add(name1+","+tami1);
           quizz.save(scoreFile);
        }
        else if (name2.equals("inFolder")){
       
        String[] sta = quizz.checkTitle(oldScore).split(",");
        if(name1.equals(sta[0]))
        {
            quizz.loadQuizz(scoreFile);
            quizz.delete(oldScore);
            oldScore=name1+","+tami1;
        quizz.add(oldScore);
        quizz.save(scoreFile);
            
        }
        }
        else{
            
           quizz.add(name1+","+tami1);
           quizz.save(scoreFile);
           quizz.add(name2+","+ tami2);
           quizz.save(scoreFile);
            
        
        }
        
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayerScore(scoreFile).setVisible(true);
            }
        });
         this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayerScore().setVisible(true);
            }
        });
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddGame().setVisible(true);
            }
        });
         this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

       
    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GuessButton;
    private javax.swing.JLabel Image;
    private javax.swing.JTextField Player1;
    private javax.swing.JTextField Player2;
    private javax.swing.JTextField ScoreField1;
    private javax.swing.JTextField ScoreField2;
    private javax.swing.JTextField jAnswer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jGameName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jQuestion;
    private javax.swing.JButton lookUpButton;
    private javax.swing.JButton newButton;
    private javax.swing.JButton nextButton;
    // End of variables declaration//GEN-END:variables

    

    
}
