/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import flow3.Controller;
import flow3.PersonalInterface;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.JOptionPane;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author Valentina
 */
public class TwoPlayers extends javax.swing.JFrame {

    /**
     * Creates new form TwoPlayers
     */
     PersonalInterface quizz;
     private String friends;
     private String play1 ;
     private String play2 ;
     private String fileName;
     
     
    public TwoPlayers() {
        initComponents();
    }

    TwoPlayers(String friends) {
        this();
    
        quizz = new Controller();
        this.friends=friends;
        fileName=friends+".txt";
        play1 = null;
        play2 = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Player1 = new javax.swing.JTextField();
        Player2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(38, 34, 47));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Play");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(333, 303, 90, 40);

        Player1.setBackground(new java.awt.Color(51, 51, 51));
        Player1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Player1.setForeground(new java.awt.Color(255, 255, 255));
        Player1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player1ActionPerformed(evt);
            }
        });
        jPanel1.add(Player1);
        Player1.setBounds(10, 40, 160, 30);

        Player2.setBackground(new java.awt.Color(51, 51, 51));
        Player2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Player2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Player2);
        Player2.setBounds(558, 40, 150, 28);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Player 2:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(650, 10, 70, 17);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Player 1:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 10, 70, 17);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Valentina\\Documents\\NetBeansProjects\\Flow3big\\src\\naruto_vs_sasuke_by_all0412-d4j36lm.jpg")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 720, 370);

        jMenu1.setText("Add Games");

        jMenuItem1.setText("Add Game");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Scores");

        jMenuItem2.setText("Player&Score");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Player");

        jMenuItem3.setText("Choose how to play");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Player1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Player1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        play1 = Player1.getText();
        play2 = Player2.getText();

        //checks if they both are added or not and saves them to the file, deleting the previous players;
        if (quizz.lookup(play2) != null) {
            //method to implement sound when you get a error message
            InputStream in;
        try{
            
        in = new FileInputStream(new File ("C:\\Users\\Valentina\\Documents\\NetBeansProjects\\Flow3big\\src\\button-12.wav"));
            AudioStream audioS= new AudioStream(in);
            AudioPlayer.player.start(audioS);
           JOptionPane.showMessageDialog(this, "Player 2 already exist! For the fairness of the game both of the players should be new!",
                   "isThere!", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
            
        }else if(quizz.lookup(play1) != null){
            InputStream in;
        try{
        in = new FileInputStream(new File ("C:\\Users\\Valentina\\Documents\\NetBeansProjects\\Flow3big\\src\\button-12.wav"));
            AudioStream audioS= new AudioStream(in);
            AudioPlayer.player.start(audioS);
           JOptionPane.showMessageDialog(this, "Player 1 already exist! For the fairness of the game both of the players should be new!",
                   "isThere!", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        }else if (play1.equals("")) {
            
            InputStream in;
        try{
        in = new FileInputStream(new File ("C:\\Users\\Valentina\\Documents\\NetBeansProjects\\Flow3big\\src\\button-12.wav"));
            AudioStream audioS= new AudioStream(in);
            AudioPlayer.player.start(audioS);
           
            
            JOptionPane.showMessageDialog(this, "Player 1 should be added!",
                    "both", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
            
            
        }else if (play2.equals("")) {
             InputStream in;
        try{
        in = new FileInputStream(new File ("C:\\Users\\Valentina\\Documents\\NetBeansProjects\\Flow3big\\src\\button-12.wav"));
            AudioStream audioS= new AudioStream(in);
            AudioPlayer.player.start(audioS);
           
            
            JOptionPane.showMessageDialog(this, "Player 2 should be added!",
                    "both", JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        }else{
            
           quizz.add(play1+","+ "0");
           quizz.save(fileName);
           quizz.add(play2+","+ "0");
           quizz.save(fileName);

        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Titles(play1, play2).setVisible(true);
            }
        });
        this.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddGame().setVisible(true);
            }
        });
         this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayerScore().setVisible(true);
            }
        });
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Player1;
    private javax.swing.JTextField Player2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
